// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comboRank1': string;
  'comboRank2': string;
  'comboRank3': string;
  'comboRank4': string;
  'comboRank5': string;
  'comboRankBadge': string;
  'comboRankNumber': string;
  'hasBadge': string;
  'icon': string;
  'icons': string;
  'searchHidden': string;
  'subclass': string;
  'subclassBase': string;
  'subclassSuperIcon': string;
  'warningIcon': string;
  'xpBar': string;
  'xpBarAmount': string;
}
export const cssExports: CssExports;
export default cssExports;
