version: '3.8'

# Development-specific configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  d2locker-dev:
    build:
      args:
        - NODE_ENV=development
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./backend:/app/backend
      # Exclude node_modules to use container's dependencies
      - /app/node_modules
      - /app/backend/node_modules
    environment:
      - NODE_ENV=development
      - WEBPACK_DEV_SERVER=true
      - HMR_ENABLED=true
    command: pnpm dev