// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armorSearchControls': string;
  'armorSearchResults': string;
  'armorTypeSection': string;
  'item': string;
  'itemGrid': string;
  'noResults': string;
  'owned': string;
  'resultsCount': string;
}
export const cssExports: CssExports;
export default cssExports;
