// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'engramsAndPostmaster': string;
  'engramsSection': string;
  'postmasterSection': string;
}
export const cssExports: CssExports;
export default cssExports;
