// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emptyEngram': string;
  'engrams': string;
  'inlineGroups': string;
  'notEquippable': string;
  'subClass': string;
  'vaultGroup': string;
  'weaponGroupingIconWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
