// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rank1': string;
  'rank2': string;
  'rank3': string;
  'rank4': string;
  'rank5': string;
  'rank6': string;
  'rank7': string;
  'rankDefault': string;
  'rankIndicator': string;
}
export const cssExports: CssExports;
export default cssExports;
