// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'average': string;
  'count': string;
  'excellent': string;
  'good': string;
  'header': string;
  'label': string;
  'poor': string;
  'rating': string;
  'ratings': string;
  'reviewSummary': string;
  'terrible': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
