// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron': string;
  'combo': string;
  'comboCount': string;
  'combos': string;
  'count': string;
  'header': string;
  'perk': string;
  'perkName': string;
  'perks': string;
  'rank': string;
  'rank1': string;
  'rank2': string;
  'rank3': string;
  'rank4': string;
  'rank5': string;
  'separator': string;
  'title': string;
  'topTraitCombos': string;
}
export const cssExports: CssExports;
export default cssExports;
