// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comboIndicator': string;
  'count': string;
  'rank': string;
  'rank1': string;
  'rank2': string;
  'rank3': string;
  'rank4': string;
  'rank5': string;
}
export const cssExports: CssExports;
export default cssExports;
