// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classIcon': string;
  'd2LmedBg': string;
  'label': string;
}
export const cssExports: CssExports;
export default cssExports;
