// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearButton': string;
  'container': string;
  'controls': string;
  'count': string;
  'noSetBonuses': string;
  'setBonusItem': string;
  'setBonusList': string;
  'syncButton': string;
}
export const cssExports: CssExports;
export default cssExports;