// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeButton': string;
  'modal': string;
  'modalBody': string;
  'modalContent': string;
  'modalHeader': string;
  'modalOverlay': string;
}
export const cssExports: CssExports;
export default cssExports;
