// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auth': string;
  'billboard': string;
  'd2LSync': string;
  'd2LSyncCheckbox': string;
  'explanation': string;
  'fineprint': string;
  'section': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
