// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'classIcon': string;
  'className': string;
  'itemLocation': string;
}
export const cssExports: CssExports;
export default cssExports;
