// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'common': string;
  'desktopActions': string;
  'desktopPopup': string;
  'desktopPopupBody': string;
  'desktopPopupRoot': string;
  'exotic': string;
  'failureReason': string;
  'header': string;
  'legendary': string;
  'mobileHeaderBottom': string;
  'mobileHeaderTop': string;
  'mobileIcon': string;
  'mobileInfo': string;
  'mobileItemActions': string;
  'mobileItemActionsBelow': string;
  'mobileItemDetails': string;
  'mobileItemHeader': string;
  'mobileItemName': string;
  'mobileMoveLocations': string;
  'mobileSource': string;
  'movePopupDialog': string;
  'popupBackground': string;
  'rare': string;
  'sheetClose': string;
  'sheetHeader': string;
  'uncommon': string;
}
export const cssExports: CssExports;
export default cssExports;
