// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyButton': string;
  'applySection': string;
  'currentSelection': string;
  'description': string;
  'itemTypeCheckboxes': string;
  'itemTypeOption': string;
  'itemTypeSelection': string;
  'preview': string;
  'shaderDetails': string;
  'shaderHeader': string;
  'shaderInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
