// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applySection': string;
  'classOption': string;
  'classOptions': string;
  'classSelection': string;
  'itemTypeCheckboxes': string;
  'itemTypeOption': string;
  'itemTypeSelection': string;
  'noShaders': string;
  'pageHeader': string;
  'preview': string;
  'selected': string;
  'shaderBulkApply': string;
  'shaderBulkApplyPage': string;
  'shaderGrid': string;
  'shaderOption': string;
  'shaderSearch': string;
  'shaderSelection': string;
}
export const cssExports: CssExports;
export default cssExports;
