// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'benefitGrid': string;
  'benefitGroup': string;
  'benefitName': string;
  'benefitOption': string;
  'benefitSelector': string;
  'benefitValue': string;
  'breakpointColor': string;
  'chart': string;
  'chartContainer': string;
  'chartHeader': string;
  'chartTitle': string;
  'enhancedColor': string;
  'legendDot': string;
  'legendItem': string;
  'legendList': string;
  'primaryColor': string;
  'pvpIndicator': string;
}
export const cssExports: CssExports;
export default cssExports;
