// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'analysisSection': string;
  'breakpoint': string;
  'breakpoints': string;
  'buildOptimizer': string;
  'buildType': string;
  'buildTypeSection': string;
  'buildTypes': string;
  'currentDistribution': string;
  'efficiency': string;
  'exceeded': string;
  'fa': string;
  'header': string;
  'hint': string;
  'met': string;
  'minimums': string;
  'notMet': string;
  'optimizeButton': string;
  'pointsControl': string;
  'priorities': string;
  'reached': string;
  'reqValue': string;
  'requirement': string;
  'requirements': string;
  'requirementsList': string;
  'resetButton': string;
  'selected': string;
  'statControl': string;
  'statGrid': string;
  'statInfo': string;
  'statInput': string;
  'statName': string;
  'statRow': string;
  'statSlider': string;
  'suggestion': string;
  'suggestions': string;
  'totalDisplay': string;
  'totalValue': string;
  'warning': string;
  'warnings': string;
}
export const cssExports: CssExports;
export default cssExports;
