// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'chartControls': string;
  'checkbox': string;
  'compareIcon': string;
  'compareToggle': string;
  'controlGroup': string;
  'controlLabel': string;
  'controlRow': string;
  'rangeControl': string;
  'rangeControls': string;
  'rangeGroup': string;
  'rangeSlider': string;
  'rangeValue': string;
  'toggle': string;
  'toggleButton': string;
  'toggleGroup': string;
  'toggles': string;
}
export const cssExports: CssExports;
export default cssExports;
