// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'applyButton': string;
  'categoryButton': string;
  'categoryButtons': string;
  'categoryFilters': string;
  'clearButton': string;
  'closeButton': string;
  'filterActions': string;
  'filterContent': string;
  'filterHeader': string;
  'filterPanel': string;
  'filterSection': string;
  'open': string;
  'panelFooter': string;
  'panelHeader': string;
  'rangeFilter': string;
  'rangeInputs': string;
  'resetButton': string;
  'searchInput': string;
  'sectionTitle': string;
  'selected': string;
  'toggleOption': string;
  'typeToggle': string;
  'typeToggles': string;
}
export const cssExports: CssExports;
export default cssExports;
