// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absolute': string;
  'categoryGroup': string;
  'categoryHeader': string;
  'compareIndicator': string;
  'percentage': string;
  'plateauBadge': string;
  'selected': string;
  'selectorHeader': string;
  'statButton': string;
  'statButtons': string;
  'statInfo': string;
  'statMeta': string;
  'statName': string;
  'statSelector': string;
  'statSource': string;
  'statUnit': string;
  'statsGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
