// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breakpoint': string;
  'breakpointIcon': string;
  'comparisonTable': string;
  'current': string;
  'efficiencyAnalysis': string;
  'efficiencyCard': string;
  'efficiencyGrid': string;
  'enhanced': string;
  'header': string;
  'insights': string;
  'locked': string;
  'maxIndicator': string;
  'maxed': string;
  'primary': string;
  'range': string;
  'rangeLabel': string;
  'rangeValue': string;
  'ranges': string;
  'recommendation': string;
  'removeIcon': string;
  'selected': string;
  'statButton': string;
  'statButtons': string;
  'statComparison': string;
  'statSection': string;
  'statSelector': string;
  'statValue': string;
  'table': string;
  'tableWrapper': string;
  'unit': string;
}
export const cssExports: CssExports;
export default cssExports;
