// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardLabel': string;
  'cardValue': string;
  'compactCard': string;
  'compactCards': string;
  'highlight': string;
  'statCard': string;
  'statHeader': string;
  'statSection': string;
  'statSource': string;
  'statTitle': string;
  'statsContainer': string;
  'statsGrid': string;
}
export const cssExports: CssExports;
export default cssExports;
