// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chartWrapper': string;
  'hoverInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
