// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loading': string;
  'logo': string;
  'logoContainer': string;
  'text': string;
  'textContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
