// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert': string;
  'alertContent': string;
  'alertLink': string;
  'alertMessage': string;
  'alertTimestamp': string;
  'alertsList': string;
  'container': string;
  'levelError': string;
  'levelInfo': string;
  'levelWarning': string;
  'noAlerts': string;
}
export const cssExports: CssExports;
export default cssExports;
