// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armorySearchControls': string;
  'armorySearchResults': string;
  'item': string;
  'itemGrid': string;
  'noResults': string;
  'owned': string;
  'resultsCount': string;
  'weaponTypeSection': string;
}
export const cssExports: CssExports;
export default cssExports;
